---
- name: create bind log dir
  file:
    path: "{{ bind__log_directory }}"
    state: directory
    owner: bind
    group: bind
    mode: 0755
  when: bind__logging

- name: bind default file
  copy:
    src: etc_default_bind9
    dest: /etc/default/bind9
  notify: Restart bind9

- name: bind named.conf.options
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    mode: 0644
  notify: Restart bind9

- name: bind named.conf.local
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
    mode: 0644
  notify: Restart bind9

# This computation assumes delay is less than 100ms between hosts (it's dirty!)
# to propagate same serial number through hosts.
- name: Compute Serial number
  set_fact:
    bind__serialnum: "{{ ( ansible_date_time.epoch|int / 100 )|int * 200 }}"

- name: bind internal domain zone
  template:
    src: db.zone
    dest: '{{ bind__zone_directory }}/db.{{ bind__internal_domain }}'
    mode: 0644
  notify: Reload bind9
  when: bind__internal_domain is defined

- name: bind additional domain zone
  template:
    src: db.additional_zone
    dest: '{{ bind__zone_directory }}/db.{{ item.name }}'
    mode: 0644
  notify: Reload bind9
  with_items: "{{ bind__additional_domains }}"
  when: bind__additional_domains is defined

- name: bind response policy zone file
  template:
    src: db.rpz
    dest: '{{ bind__rpz_zone_file }}'
    mode: 0644
  notify: Reload bind9
  when:
    - bind__rpz_static is defined or bind__rpz_cname is defined

- name: bind response policy zone deletion
  file:
    path: "{{ bind__rpz_zone_file }}"
    state: absent
  when:
    - bind__rpz_static is not defined
    - bind__rpz_cname is not defined

- name: bind internal domain reverse zones
  template:
    src: db.rev
    dest: "{{ bind__zone_directory }}/db.{{ bind__internal_network|replace('/', '-') }}.rev"
    mode: 0644
  when:
    - bind__internal_network is defined
    - bind__internal_network != None
    - bind__known_networks is not defined or bind__internal_network not in bind__known_networks
  notify: Reload bind9

- name: bind known domains reverse zones (may contain internal network)
  template:
    src: db.known.rev
    dest: "{{ bind__zone_directory }}/db.{{ item|replace('/', '-') }}.rev"
    mode: 0644
  with_items: "{{ bind__known_networks }}"
  when:
    - bind__known_networks is defined and bind__known_networks != None
  notify: Reload bind9
