---
- import_tasks: install.yml
  when:
    - bind__install

- import_tasks: conf-server.yml
  when:
    - bind__install
    - bind__configure

- import_tasks: conf-client.yml
  when:
    - bind__client_configure
...
